### ISSUE TITLE
Example doesn't seem to work

### ISSUE THREAD

**Issue by duck-dev-go** [MajedDH/bring_to_foreground#3] opened 2020-07-07 15:16 UTC
@MajedDH I am using flutter 1.17.5 and if I run the example code on my Huawei p30 with android 10, then I brin the app to the background the app will never be brought back to the foreground on a tick of the timer.

```
import 'dart:async';

import 'package:bringtoforeground/bringtoforeground.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    String platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      Timer.periodic(Duration(seconds: 10), (t) {
        print('tick ${t.tick}');
        Bringtoforeground.bringAppToForeground();
        print('after trying to bring app to foreground');
      });
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
      print('platform exception');
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    print('not mounted');

    setState(() {
      _platformVersion = platformVersion;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Text('Running on: $_platformVersion\n'),
        ),
      ),
    );
  }
}
```

And this is the output

```
Launching lib\main.dart on VOG L29 in profile mode...
√ Built build\app\outputs\apk\profile\app-profile.apk (9.2MB).
Connecting to VM Service at ws://127.0.0.1:56395/cJGh6nGpAVQ=/ws
I/flutter (31519): not mounted
W/Settings(31519): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(31519): User setup is finished.
W/HiTouch_PressGestureDetector(31519): Touch pointer move a lot. The moving distance of X is:51.0, limit is:60The moving distance of Y is:68.0, limit is:60
W/libEGL  (31519): EGLNativeWindowType 0x781f47b010 disconnect failed
W/libEGL  (31519): EGLNativeWindowType 0x787de21f50 disconnect failed
D/ZrHung.AppEyeUiProbe(31519): not watching, wait.
I/AwareBitmapCacher(31519): init lrucache size: 2097152 pid=31519
I/flutter (31519): tick 1
I/flutter (31519): after trying to bring app to foreground
D/HwFrameworkSecurityPartsFactory(31519): HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory(31519): add HwFrameworkSecurityPartsFactory to memory.
I/flutter (31519): tick 2
I/flutter (31519): after trying to bring app to foreground
```

**Comment by MajedDH** [comment] 2020-07-16 11:51
Duplicate of #5 

Closing as a duplicate of #5. we can continue the discussion there.

**Closed as completed by MajedDH** 2020-07-16 11:51 UTC
